-- DDL：テーブル作成
CREATE TABLE sampleMath (
  m  NUMERIC (10, 3),
  n  INTEGER,
  p  INTEGER
);

-- DML：データ登録
BEGIN TRANSACTION;

INSERT INTO sampleMath VALUES (500, 0, NULL);
INSERT INTO sampleMath VALUES (-180, 0, NULL);
INSERT INTO sampleMath VALUES (NULL, NULL, NULL);
INSERT INTO sampleMath VALUES (NULL, 7, 3);
INSERT INTO sampleMath VALUES (NULL, 5, 2);
INSERT INTO sampleMath VALUES (NULL, 4, NULL);
INSERT INTO sampleMath VALUES (8, NULL, 3);
INSERT INTO sampleMath VALUES (2.27, 1, NULL);
INSERT INTO sampleMath VALUES (5.555, 2, NULL);
INSERT INTO sampleMath VALUES (NULL, 1, NULL);
INSERT INTO sampleMath VALUES (8.76, NULL, NULL);

COMMIT;